# Generated by Django 5.0.7 on 2024-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('directed_by', models.CharField(max_length=255)),
                ('storyboarded_by', models.CharField(max_length=255)),
                ('original_air_date', models.DateField(max_length=10)),
                ('summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
