# Generated by Django 5.0.7 on 2024-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='written_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
