# Generated by Django 5.0.7 on 2024-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_episode_written_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=4)),
                ('voiced_by', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
