# Generated by Django 5.0.7 on 2024-07-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_character_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='voiced_by',
            new_name='voice_actors',
        ),
    ]
